version: '3.4'
services:
  achat:
    image: achat
    hostname: achatapp
    environment:
      - DB_HOST=172.20.199.3
      - DB_USER=root
      - DB_PWD=1234
      - spring.jpa.hibernate.ddl-auto=update
    expose:
      - "8082"
    restart: on-failure:3
    ports:
      - "8089:8089"
    depends_on:
      - mysql
    networks:
      achatNetwork:
        ipv4_address: 172.20.199.2
  mysql:
    image: mysql:8.0.28
    hostname: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: achatdb
    networks:
      achatNetwork:
        ipv4_address: 172.20.199.3
networks:
  achatNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.199.1/24
