version: '3,8'
services:
  api:
    image: ouday0011/achat
    container_name: achat
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    depends_on:
      - ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
            "server.port" : "$SPRING_LOCAL_PORT",
            "spring.datasource.url" : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?createDatabaseIfNotExist=true",
            "spring.datasource.username" : "$MYSQLDB_USER"
            "spring.datasource.password" : "$MYSQLDB ROOT PASSWORD",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.hibernate.ddl-auto" :"update"
          }'
    restart: on-failure
  db:
    image: mysql
    container_name: mysqldb
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    environment:
      - MYSQL_DB=${MYSQLDB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
  adminer:
    image: adminer
    ports:
      - '8082:8080'
    restart: unless-stopped

  volumes:
    db